### ISSUE TITLE
Update theme to hilight whole lines

### ISSUE THREAD

**Issue by ybart** [miketheman/language-diff#13]
I thought it would be great to hilight the whole diffed lines, so I ended using the following stylesheet:

```less
atom-text-editor::shadow {
  .line {
    position: relative;

    .meta.diff.header::after, .meta.diff.index::after,
    .markup.inserted.diff::after, .markup.deleted.diff::after {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      display: block;
      z-index: -100;
      content: '';
    }

    .meta.diff.header::after, .meta.diff.index::after {
      background-color: #113050;
    }

    .markup.inserted.diff::after {
      background-color: #224422;
    }

    .markup.deleted.diff::after {
      background-color: #442222;
    }

    .markup.inserted.diff {
      color: #ccffcc;
    }

    .markup.deleted.diff {
      color: #ddaaaa;
    }
  }
}
```

It renders well with my theme (solarized-dark), but colors might need to be changed to use theme colors.

Here is a preview:

<img width="694" alt="capture d ecran 2017-08-09 a 11 05 22" src="https://user-images.githubusercontent.com/223016/29113875-ab94c7b8-7cf2-11e7-942e-3b4dfb8388fd.png">

I got the CSS from here : https://discuss.atom.io/t/highlight-entire-line-depending-on-syntax/20653
